Repository monorepolint/monorepolint, pull requests merged in 2018-12, with the labels that each got.

#16 Requires force-publish for lerna publish
  package.json
Labels: chore

#11 Adds CHANGELOG.md
  .github_changelog_generator
  CHANGELOG.md
  README.md
  package.json
Labels: chore

#22 Adds tests for shouldSkipPackage
  packages/core/src/__tests__/shouldSkipPackage.spec.ts
  packages/core/src/check.ts
Labels: chore

#21 Renames `@monorepo-lint/all` to `monorepolint`
  .github_changelog_generator
  .monorepolint.config.ts
  CHANGELOG.md
  LICENSE
  README.md
  package.json
  packages/all/package.json
  packages/cli/bin/monorepolint
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/core/package.json
  packages/core/src/Config.ts
  packages/core/src/Context.ts
  packages/core/src/PackageContext.ts
  packages/core/src/WorkspaceContext.ts
  packages/core/src/check.ts
  packages/core/src/index.ts
  packages/core/src/resolveConfig.ts
  packages/rule-alphabetical-dependencies/package.json
  packages/rule-alphabetical-dependencies/src/alphabeticalDependencies.ts
  packages/rule-banned-dependencies/package.json
  packages/rule-banned-dependencies/src/bannedDependencies.ts
  packages/rule-consistent-dependencies/package.json
  packages/rule-consistent-dependencies/src/consistentDependencies.ts
  packages/rule-file-contents/package.json
  packages/rule-file-contents/src/fileContents.ts
  packages/rule-package-order/package.json
  packages/rule-package-order/src/packageOrder.ts
  packages/rule-package-script/package.json
  packages/rule-package-script/src/__tests__/packageScript.spec.ts
  packages/rule-package-script/src/packageScript.ts
  packages/rule-standard-tsconfig/package.json
  packages/rule-standard-tsconfig/src/standardTsconfig.ts
  packages/utils/package.json
  packages/utils/src/PackageJson.ts
  packages/utils/src/findWorkspaceDir.ts
  packages/utils/src/getPackageNameToDir.ts
  packages/utils/src/getWorkspacePackageDirs.ts
  packages/utils/src/index.ts
  packages/utils/src/readJson.ts
  packages/utils/src/writeJson.ts
  tslint.json
Labels: breaking

#23 Updates prettier config to 120 and trailing commas
  .prettierrc
  packages/cli/src/index.ts
  packages/core/src/Config.ts
  packages/core/src/PackageContext.ts
  packages/core/src/__tests__/shouldSkipPackage.spec.ts
  packages/core/src/check.ts
  packages/core/src/index.ts
  packages/core/src/resolveConfig.ts
  packages/rule-alphabetical-dependencies/src/alphabeticalDependencies.ts
  packages/rule-banned-dependencies/src/bannedDependencies.ts
  packages/rule-consistent-dependencies/src/consistentDependencies.ts
  packages/rule-file-contents/src/fileContents.ts
  packages/rule-package-order/src/packageOrder.ts
  packages/rule-package-script/src/__tests__/packageScript.spec.ts
  packages/rule-package-script/src/packageScript.ts
  packages/rule-standard-tsconfig/src/standardTsconfig.ts
  packages/utils/src/getWorkspacePackageDirs.ts
Labels: chore

#24 Adds back multiplicity in the form of an array as a the value for the package key
  .circleci/config.yml
  jest.config.base.js
  packages/core/src/Config.ts
  packages/core/src/resolveConfig.ts
Labels: enhancement

#25 Makes clean delete more
  .monorepolint.config.ts
  package.json
  packages/all/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/rule-alphabetical-dependencies/package.json
  packages/rule-banned-dependencies/package.json
  packages/rule-consistent-dependencies/package.json
  packages/rule-file-contents/package.json
  packages/rule-package-order/package.json
  packages/rule-package-script/package.json
  packages/rule-standard-tsconfig/package.json
  packages/utils/package.json
Labels: chore

#26 Maclockard/reorg
  packages/all/package.json
  packages/all/tsconfig.json
  packages/core/package.json
  packages/core/src/resolveConfig.ts
  packages/rule-alphabetical-dependencies/package.json
  packages/rule-banned-dependencies/jest.config.js
  packages/rule-banned-dependencies/package.json
  packages/rule-banned-dependencies/tsconfig.json
  packages/rule-consistent-dependencies/jest.config.js
  packages/rule-consistent-dependencies/package.json
  packages/rule-consistent-dependencies/tsconfig.json
  packages/rule-file-contents/jest.config.js
  packages/rule-file-contents/package.json
  packages/rule-file-contents/tsconfig.json
  packages/rule-package-order/jest.config.js
  packages/rule-package-order/package.json
  packages/rule-package-order/tsconfig.json
  packages/rule-package-script/jest.config.js
  packages/rule-package-script/package.json
  packages/rule-package-script/tsconfig.json
  packages/rule-standard-tsconfig/jest.config.js
  packages/rule-standard-tsconfig/tsconfig.json
  packages/rules/jest.config.js
  packages/rules/package.json
  packages/rules/src/__tests__/packageScript.spec.ts
  packages/rules/src/alphabeticalDependencies.ts
  packages/rules/src/bannedDependencies.ts
  packages/rules/src/consistentDependencies.ts
  packages/rules/src/fileContents.ts
  packages/rules/src/index.ts
  packages/rules/src/packageOrder.ts
  packages/rules/src/packageScript.ts
  packages/rules/src/standardTsconfig.ts
  packages/rules/tsconfig.json
  yarn.lock
Labels: breaking

#29 Enables type inference from yargs
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/core/src/Config.ts
  yarn.lock
Labels: chore
